project:
  title: "CO2RR Database Demo"
  type: website
  render:
    - index.qmd
    - potential.qmd
    - source.qmd

website:
  navbar:
    title: false
    search: false
    background: "none"
    left:
      - text: Overview
        href: index.qmd
        icon: bar-chart
      - text: Potential
        href: potential.qmd
        icon: activity
      - text: Source
        href: source.qmd
        icon: journal-text

format:
  datapage-html:
    theme: [resources/scss/theme.scss, resources/scss/layout.scss]
    mainfont: "Times New Roman, Times, serif"
    callout-icon: false

execute: 
  echo: false
  message: false
  warning: false
  error: false

resources:
  - "resources/fonts/*"
